FROM pytorchlightning/pytorch_lightning:base-cuda-py3.9-torch1.11

COPY artifact/setup/requirements.txt /opt/app/requirements.txt

WORKDIR /opt/app

RUN pip install -r requirements.txt 

# Packages that require runtime download can be cached by running the python -c "CODE"
# Replace "CODE" with the lines that handle downloading
# RUN python -c "CODE"

WORKDIR /workspace